#!/usr/bin/awk -f
BEGIN {FS=":";none=0} 
#Si la expresion regular es igual que el valor de algun campo 2, imprime el campo 2 y despues el 1, que es el numero de campo
$2~RE{
	c1=$1;
	c2=$2;
}
#Si no se pasa ninguna expresion regular, imprime -1
""~RE{
	none=1;
}
#Si c2 es vacío, es decir, no ha encontrado ninguna vez el patron, imprime 0
END{
	if(none==1){
		print -1;
	}else if (c2==""){
		print 0;
	}else
		print c1;	

}
